name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  BuildAndTest:
    name: Build and Test on JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Build project
        run: ./gradlew build
      - name: Archive UnitTest report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: UnitTest-report
          path: ${{ github.workspace }}/**/build/reports/tests/testDebugUnitTest
  Espresso:
    runs-on: macOS-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
        with:
          cmd: ./gradlew clean build connectedCheck
          api: 28
          tag: default
          abi: x86
      - name: Archive Espresso results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Espresso-report
          path: ./**/build/reports/androidTests/connected